apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc1
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0706be8946f71ae1b
  # hostPath:
  #   path: /tmp

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc1
  resources:
    requests:
      storage: 5Gi